LOGIN_REQUIRED = 'Es necesario iniciar sesion'
USER_CREATED = 'Usuario creado'
LOGOUT = 'Cerraste sesion'
LOGIN = 'Usuario autenticado'
ERROR_USER_PASSWORD = 'Usuario o password incorrectos'
TASK_CREATED = 'Tarea creada'
TASK_UPDATED = 'Tarea editada'
TASK_DELETE = 'Tarea eliminada'